# ESemail 配置文件示例（请复制为 config/config.yaml 并按需修改）

# 说明：
# - 推荐在生产环境中使用系统级 Postfix/Dovecot 作为邮件服务核心。
# - 本应用提供 Web/API、初始化流程、DNS/证书辅助与可选的内置 SMTP/IMAP（开发用途）。
# - 强烈建议设置 cert.email 为有效邮箱，用于 ACME 证书申请（Let's Encrypt）。

server:
  # Web/API 监听端口与网络模式
  port: "8686"           # 对外暴露的管理端口
  host: "0.0.0.0"       # 监听地址（生产中可限制为内网IP）
  mode: "release"        # gin 模式: release/debug
  read_timeout: 30s       # 读取超时
  write_timeout: 30s      # 写入超时
  shutdown_timeout: 10s   # 优雅退出超时
  max_header_bytes: 1048576  # 最大请求头大小（字节）

database:
  # 账号/配置等持久化存储，默认使用JSON文件
  type: "json"           # 可扩展: postgres/mysql（当前项目以json为主）
  path: "./data/db"      # 数据库文件目录（json模式有效）
  host: "localhost"
  port: 5432
  username: ""
  password: ""
  database: "esemail"
  ssl_mode: "disable"
  max_open_conns: 10
  max_idle_conns: 5

mail:
  # 生产环境优先使用系统级 Postfix/Dovecot。
  # 以下端口用于“内置”SMTP/IMAP（开发/演示），生产可忽略。
  domain: "yourdomain.com"     # 邮件域名（例如 caiji.wiki）
  data_path: "./mail"          # 内置邮件存储路径（Maildir 等）
  log_path: "./logs"           # 应用日志目录
  domains: []                   # 额外域名列表（可选）
  admin_email: "admin@yourdomain.com" # 管理员邮箱（用于初始化与通知）
  smtp_port: "2525"            # 内置 SMTP（开发用途）
  smtps_port: "4465"           # 内置 SMTPS（开发用途）
  imap_port: "1143"            # 内置 IMAP（开发用途）
  imaps_port: "9993"           # 内置 IMAPS（开发用途）
  enable_tls: false             # 内置协议是否启用TLS（生产建议false，由系统级MTA处理TLS）
  tls_cert_file: ""             # 内置TLS证书（生产留空）
  tls_key_file: ""              # 内置TLS私钥（生产留空）
  max_message_size: 26214400    # 最大邮件大小（字节），默认25MB
  max_recipients: 100           # 单封邮件最大收件人数量
  queue_retries: 3              # 内置队列重试次数
  queue_interval: 30s           # 队列处理间隔
  retry_interval: 5m            # 重试间隔
  max_concurrent: 10            # 最大并发队列处理数

cert:
  # ACME/证书配置（用于邮件域名的 TLS 证书，如 mail.yourdomain.com）
  cert_path: "/etc/ssl/mail"   # 证书安装路径（系统级服务通常从此读取）
  server: "letsencrypt"        # ACME 服务：letsencrypt/staging/自定义目录URL
  email: "admin@yourdomain.com" # 必填！证书申请联系人邮箱（必须为有效域名邮箱）

storage:
  # 统一数据存储目录（域名、用户、工作流状态等 JSON 文件）
  data_dir: "./data"
  backup_dir: "./backups"
  max_file_size: 104857600      # 单文件最大大小（字节）
  cleanup_days: 30              # 清理历史/临时文件的保留天数

security:
  # 安全设置（生产环境务必替换密钥）
  jwt_secret: "请替换为强随机字符串"   # JWT 签名密钥
  jwt_expiration: 24h              # JWT 过期时间
  csrf_secret: "请替换为强随机字符串"  # CSRF 密钥（Cookie 签名等）
  rate_limit_enabled: true
  rate_limit_rps: 100             # 每秒请求数
  rate_limit_burst: 200           # 突发请求数
  allowed_origins: ["http://localhost:8686"]  # 允许的跨域来源
  trusted_proxies: []             # 受信任的代理（如 Nginx/Ingress 的 IP）

logging:
  # 日志输出与滚动
  level: "info"                 # 日志级别：debug/info/warn/error
  format: "json"                # 输出格式：json/text
  output: "stdout"              # 输出位置：stdout/file
  file: ""                      # 当 output=file 时生效
  max_size: 100                  # 单日志文件最大MB
  max_backups: 3                 # 保留历史文件数
  max_age: 7                     # 保留天数
  compress: true                 # 是否压缩
  enable_caller: true            # 是否输出调用位置

# 使用说明：
# 1) 复制本文件为 config/config.yaml 并根据环境修改。
# 2) 启动前导出环境变量指向此文件：
#    export ESEMAIL_CONFIG=$(pwd)/config/config.yaml
# 3) 或者在 systemd/容器环境中通过环境变量注入 ESEMAIL_CONFIG。
# 4) 生产环境请确保系统已安装并启用：postfix、dovecot、opendkim、rspamd、fail2ban 等。
